name: jago # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.9.5.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Jago is a Go playing app
description: |
    Jago is a Go playing app written in Java

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  jago_icon.png
title: Jago

apps:
  jago:
    command: startjago
parts:
  jago:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
    build-packages: [default-jre]
    stage-packages: [default-jre]
    organize:
      jago: build/
      jago.1: man/man1/

architectures:
  - build-on: amd64

